#!/usr/bin/openrc-run
description="DHCP Client Daemon"

command="/usr/bin/dhcpcd"
command_args="-q -B ${command_args:-}"
command_background="true"
pidfile="/run/dhcpcd/pid"

depend() {
    need io-sock
    provide net
}


start_pre() {
    checkpath -d /run/dhcpcd

    if getent passwd "dhcpcd" >/dev/null 2>&1 && getent group "dhcpcd" >/dev/null 2>&1; then
        # we need to allow the dhcpcd user access to /dev/bpf
        setfacl -m u:dhcpcd:rw- /dev/bpf
        setfacl -m g:dhcpcd:rw- /dev/bpf
    else
        ewarn "dhcpcd user or group missing will not drop privledges"
    fi
}

